server:
  port: 8081

---
spring:
  profiles: default

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    url: jdbc:postgresql://localhost:5432/fees
    username: acme
    password: acme
    driver-class-name: org.postgresql.Driver

logging:
  level:
    com.acme: DEBUG



